version: '3'
services:
  db:
    hostname: todo-db
    image: postgres:13.4-alpine3.14
    volumes:
      - database_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=app_development
  web:
    build: .
    volumes:
      - .:/app:cached
    ports:
      - "3000:3000"
    environment:
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=password
      - DATABASE_DB=app_development
    depends_on:
      - db

volumes:
  database_data:
